### PR TITLE
[BaseDataTransaction+Importing] Fix import of unique objects with reflexive relationships.

### PR DESCRIPTION
**Pull request by ruslanskorb**

### CODE REVIEW

**Comment by JohnEstropia** [comment]
@ruslanskorb Thanks for the PR. I'm not sure what case this covers though. Can you describe what edge case is being handled here?

**Comment by ruslanskorb** [comment]
@JohnEstropia Something like this:

```swift
class SomeObject: NSManagedObject, ImportableUniqueObject {
    
    @NSManaged var reflexiveRelationship: SomeObject?
    
    @NSManaged var uniqueID: Int?
    
    ...
}

let someObjectJSON1 = [
    
    "uniqueID": 1,
    "reflexiveRelationship": [
        
        "uniqueID": 2,
        "reflexiveRelationship": null
    ]
]
let someObjectJSON2 = [
    
    "uniqueID": 2,
    "reflexiveRelationship": null
]

let jsons = [
    
    someObjectJSON1,
    someObjectJSON2
]

try transaction.importUniqueObjects(Into<SomeObject>(), sourceArray: jsons)
```

**Comment by JohnEstropia** [comment]
I see, so it's to delete relationships through import keys. The current import mechanism intentionally doesn't handle relationships, and I think the sudden support for `null`ing out objects is a breaking behavior, so I don't think I can merge this to the main branch.

To explain why relationships are not managed in imports, apps are free to implement "deletions" in the `ImportSource`, but there are a lot of reasonable choices here:
- clients may just `null` out the relationship and leave the object instance alive (same in your PR) 
- clients may delete the object from the store
- clients may ignore the `null` value
- clients may mark an object's `pendingDeletion` flag or something similar, and do the actual handling later on
- etc.

This PR only considers the first case, so I'll have to reject it. Feel free to continue the discussion in this thread, but I'll close the PR for now.

**Comment by JohnEstropia** [comment]
Wait, sorry I totally misunderstood your example. I'll have to check your code again because I think I get the use case, but the approach defeats the purpose of the efficient batch-fetching.

**Comment by JohnEstropia** [comment]
@ruslanskorb I've thought about this implementation and was torn about the increase of complexity, but decided that the issue being addressed is dangerous enough to be ignored. I implemented your approach using safer internal casting that supports both `NSManagedObject` and `CoreStoreObject` subclasses: https://github.com/JohnEstropia/CoreStore/commit/edd8ba55d8ea6d4b0c921d1e1bcfc5eb8ea53ccc#diff-a283ded009251a25e2a7de48aec450cc5ce13676fd23e668f2fbb62ad53c00d9R235

I'm closing this PR, but please do try out the develop branch and let me know if you find issues. Thanks again for raising this edge case

**Comment by ruslanskorb** [comment]
@JohnEstropia Ok, thanks for taking a look at this.

**Pull request closed without merging**
