### PR TITLE
Add convenient truncate methods to transaction

### PR DESCRIPTION
**Pull request by AleksandarPetrov**
Provides a convenient method for deleting all entities from DataStack with the ability to preserve some entities.

Sample usage:
```
transaction.truncateDataStack(shouldSkip: { (entity) -> Bool in
    return (entity == Favorite.self)
})
```

### CODE REVIEW

**Comment by JohnEstropia** [comment]
There's an easier way to do this without a separate method:
```swift
CoreStore.beginAsynchronous { (transaction) in

    transaction.deleteAll(From(NSManagedObject))
    transaction.commit()
}
```

**Comment by JohnEstropia** [comment]
Oh, sorry. I realized that you are checking the class type, not a variable.
Hmm...

**Comment by AleksandarPetrov** [comment]
Probably my example is not very good without context. I'm checking the class type in order to skip it from deleting. I'll try your solution it's really simple. I don't know how I didn't figure it out myself

**Comment by JohnEstropia** [comment]
I thought about if, but I believe this functionality should be app-specific for several reasons:

1. A truncate that deletes "everything except X" sounds dangerous; each time a new Entity is added to the model you would need to consider updating the truncate targets as well. If you miss anything, your users will lose data.
2. CoreStore supports multiple configurations, so an API that doesn't consider a `From` clause's `configurations` argument won't match several use cases.
3. Filtering by class seems confusing when subclasses come into play.

In any case, `entityTypesByName` is not thread-safe, so it should be accessed in the main thread and not within the transaction:
```swift
let entityTypes = CoreStore.entityTypesByName.values
CoreStore.beginSynchronous { (transaction) -> Void in
    
    entityTypes
        .filter { $0 != Favorite.self }
        .forEach { transaction.deleteAll(From($0)) }
        
    transaction.commitAndWait()
}
```

**Comment by AleksandarPetrov** [comment]
I see your point and you're right. Thanks for sharing this great snippet!

**Comment by JohnEstropia** [comment]
I'm closing this pull request, but feel free to extend CoreStore in your own app and share other ideas :)

**Pull request closed without merging**
