### PR TITLE
Allows to set custom options for SQLite store

### PR DESCRIPTION
**Pull request by mantas**
This patch allows to modify options when creating a SQLite persistent store

### CODE REVIEW

**Comment by JohnEstropia** [comment]
hmm, this looks ok but I'd rather have the dictionary as an argument to `addSQLiteStore()`. The current implementation does not make guarantees when the options will be applied, and the DataStack makes assumptions that the default store is in WAL journaling (it deletes the -shm file on migration, for example). 

Most API users probably won't care though.

May I know what use case you have for needing to change the default options?

**Comment by mantas** [comment]
I was thinking about adding it as an option to addSQLiteStore/addSQLiteStoreAndWait too. But it seemed to be more flexible and quicker to implement by making the defaults mutable. In addition to that, it plays nicer with ObjectiveC.

Would you prefer it as an option for addSQLiteStore(andWait)? That'd work for me too.

I'm using this to enable lightweight migrations for addSQLiteStoreAndWait()

**Comment by JohnEstropia** [comment]
@mantas Here's an idea, we can keep the previous `optionsForSQLiteStore()` method `internal`, but expose another `public` property we can use to append to the default value. That way we can still guarantee that the WAL journal mode is still set. Something like
```swift
internal func optionsForSQLiteStore() -> [String: AnyObject] {

    var options: [String: AnyObject] = [NSSQLitePragmasOption: ["journal_mode": "WAL"]]
    self.extraOptionsForSQLiteStore.forEach { options[$0] = $1 }
    return options
}

public var extraOptionsForSQLiteStore: [String: AnyObject] = []
```

What do you think?

**Comment by mantas** [comment]
Works for me

**Comment by JohnEstropia** [comment]
@mantas Are you willing to update the PR or should I implement it directly on the master branch?

**Comment by mantas** [comment]
@JohnEstropia I'll update the PR.

**Comment by JohnEstropia** [comment]
ok, thanks!

**Comment by JohnEstropia** [comment]
I'll be closing this for now since this ability has been added to the upcoming CoreStore v2 (see the corestore2_develop branch (work in progress)). If you're still interested to make a pull request, feel free to make the necessary changes and reopen the PR.

**Pull request closed without merging**
